export const data = [
  {
    licenseId: "LIC-2001",
    user: {
      id: "USR-101",
      name: "Atif Khan",
      email: "atif.khan@example.com",
      phone: "+92-300-1234567",
      address: "123 Model Town, Lahore, Pakistan",
      country: "Pakistan",
      profileImg: "https://randomuser.me/api/portraits/men/32.jpg",
    },
    licenseType: "Driver",
    issuedDate: "2023-05-10",
    expiryDate: "2026-05-10",
    status: "Active",
  },
  {
    licenseId: "LIC-2002",
    user: {
      id: "USR-102",
      name: "Aarav Sharma",
      email: "aarav.sharma@example.com",
      phone: "+91-9876543210",
      address: "MG Road, Bangalore, India",
      country: "India",
      profileImg: "https://randomuser.me/api/portraits/men/15.jpg",
    },
    licenseType: "Business",
    issuedDate: "2022-07-01",
    expiryDate: "2027-07-01",
    status: "Active",
  },
  {
    licenseId: "LIC-2003",
    user: {
      id: "USR-103",
      name: "Sara Ahmed",
      email: "sara.ahmed@example.com",
      phone: "+880-1711-223344",
      address: "Dhanmondi, Dhaka, Bangladesh",
      country: "Bangladesh",
      profileImg: "https://randomuser.me/api/portraits/women/45.jpg",
    },
    licenseType: "Medical",
    issuedDate: "2021-11-20",
    expiryDate: "2024-11-20",
    status: "Expired",
  },
  {
    licenseId: "LIC-2004",
    user: {
      id: "USR-104",
      name: "Miguel Santos",
      email: "miguel.santos@example.com",
      phone: "+63-917-5556677",
      address: "Quezon City, Manila, Philippines",
      country: "Philippines",
      profileImg: "https://randomuser.me/api/portraits/men/66.jpg",
    },
    licenseType: "Software",
    issuedDate: "2024-02-15",
    expiryDate: "2028-02-15",
    status: "Pending",
  },
  {
    licenseId: "LIC-2005",
    user: {
      id: "USR-105",
      name: "Zoya Malik",
      email: "zoya.malik@example.com",
      phone: "+92-333-8889990",
      address: "DHA Phase 5, Karachi, Pakistan",
      country: "Pakistan",
      profileImg: "https://randomuser.me/api/portraits/women/29.jpg",
    },
    licenseType: "Teacher",
    issuedDate: "2020-09-10",
    expiryDate: "2025-09-10",
    status: "Active",
  },
];
